
//counter
export const COUNTER_RESET = 'COUNTER_RESET';
export const COUNTER_MULT = 'COUNTER_MULT';
export const COUNTER_RESETMULT = 'COUNTER_RESETMULT';

//global
export const HANDLE_NETWORK_CHANGE = 'HANDLE_NETWORK_CHANGE'


//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_CLEAR_FAILED = 'LOGIN_CLEAR_FAILED';
export const LOGIN_GET_FCM = 'LOGIN_GET_FCM'

//logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

//vehicleList

export const VEHICLELIST_REQUEST = 'VEHICLELIST_REQUEST';
export const VEHICLELIST_RESPONSE = 'VEHICLELIST_RESPONSE';
export const VEHICLELIST_FAILED = 'VEHICLELIST_FAILED';

//LiveTracking
export const LIVETRACKING_REQUEST = 'LIVETRACKING_REQUEST';
export const LIVETRACKING_RESPONSE = 'LIVETRACKING_RESPONSE';
export const LIVETRACKING_FAILED = 'LIVETRACKING_FAILED';

//driverList

export const DRIVERLIST_REQUEST = 'DRIVERLIST_REQUEST';
export const DRIVERLIST_RESPONSE = 'DRIVERLIST_RESPONSE';
export const DRIVERLIST_FAILED = 'VEHICLELIST_FAILED';

//alarmList

export const ALARM_LIST_REQUEST = 'ALARM_LIST_REQUEST';
export const ALARM_LIST_RESPONSE = 'ALARM_LIST_RESPONSE';
export const ALARM_LIST_FAILED = 'ALARM_LIST_FAILED';

//vehicledetailList

export const VEHICLE_DETAILLIST_REQUEST = 'VEHICLE_DETAILLIST_REQUEST';
export const VEHICLE_DETAILLIST_RESPONSE = 'VEHICLE_DETAILLIST_RESPONSE';
export const VEHICLE_DETAILLIST_FAILED = 'VEHICLE_DETAILLIST_FAILED';
export const VEHICLE_DETAILLIST_CHANGE_SCREEN = 'VEHICLE_DETAILLIST_CHANGE_SCREEN';
export const VEHICLE_MOBILIZE_REQUEST = 'VEHICLE_MOBILIZE_REQUEST';
export const VEHICLE_IMMOBILIZE_REQUEST = 'VEHICLE_IMMOBILIZE_REQUEST';
export const VEHICLE_MOBILIZE_RESPONSE = 'VEHICLE_MOBILIZE_RESPONSE';
export const VEHICLE_IMMOBILIZE_RESPONSE = 'VEHICLE_IMMOBILIZE_RESPONSE';

//driverDetailList
export const DRIVER_DETAILLIST_REQUEST = 'DRIVER_DETAILLIST_REQUEST';
export const DRIVER_DETAILLIST_RESPONSE = 'DRIVER_DETAILLIST_RESPONSE';
export const DRIVER_DETAILLIST_FAILED = 'DRIVER_DETAILLIST_FAILED';
export const DRIVER_DETAILLIST_CHANGE_SCREEN = 'DRIVER_DETAILLIST_CHANGE_SCREEN';

//TripHistoryList

export const TRIP_HISTORY_REQUEST = 'TRIP_HISTORY_REQUEST';
export const TRIP_HISTORY_RESPONSE = 'TRIP_HISTORY_RESPONSE';
export const TRIP_HISTORY_FAILED = 'TRIP_HISTORY_FAILED';
export const TRIP_HISTORY_MESSAGEBOX = 'TRIP_HISTORY_MESSAGEBOX';

//detailList

export const TRIP_HISTORY_DETAIL_REQUEST = 'TRIP_HISTORY_DETAIL_REQUEST';
export const TRIP_HISTORY_DETAIL_RESPONSE = 'TRIP_HISTORY_DETAIL_RESPONSE';
export const TRIP_HISTORY_DETAIL_FAILED = 'TRIP_HISTORY_DETAIL_FAILED';

//NotificationList

export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_RESPONSE = 'NOTIFICATION_LIST_RESPONSE';
export const NOTIFICATION_STATUS_UPDATE = 'NOTIFICATION_STATUS_UPDATE';


//loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const RESET_SUCCESS_LOADING = 'RESET_SUCCESS_LOADING';
export const IS_KEYBOARD = 'IS_KEYBOARD';


export const MESSAGEBOX_ENABLE='MESSAGEBOX_ENABLE'
export const MESSAGEBOX_DISABLE='MESSAGEBOX_DISABLE'


export const INTERNALERROR_MESSAGEBOX_ENABLE='INTERNALERROR_MESSAGEBOX_ENABLE'
export const INTERNALERROR_MESSAGEBOX_DISABLE='INTERNALERROR_MESSAGEBOX_DISABLE'